//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DBCONCESSIONARIAEntities : DbContext
    {
        public DBCONCESSIONARIAEntities()
            : base("name=DBCONCESSIONARIAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<VEI001_MARCA> VEI001_MARCA { get; set; }
        public virtual DbSet<VEI002_MODELO> VEI002_MODELO { get; set; }
        public virtual DbSet<VEI003_COMBUSTIVEL> VEI003_COMBUSTIVEL { get; set; }
        public virtual DbSet<VEI004_MODELO_VERSAO> VEI004_MODELO_VERSAO { get; set; }
        public virtual DbSet<VND001_VENDEDOR> VND001_VENDEDOR { get; set; }
        public virtual DbSet<VND002_VENDA> VND002_VENDA { get; set; }
    
        public virtual ObjectResult<ListarComissoesVendedores_Result> ListarComissoesVendedores()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarComissoesVendedores_Result>("ListarComissoesVendedores");
        }
    }
}
