//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEI004_MODELO_VERSAO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VEI004_MODELO_VERSAO()
        {
            this.VND002_VENDA = new HashSet<VND002_VENDA>();
        }
    
        public int IdeModeloVersao { get; set; }
        public int IdeModelo { get; set; }
        public byte IdeCombustivel { get; set; }
        public Nullable<short> NroAno { get; set; }
        public decimal VlrPrecoTabelado { get; set; }
    
        public virtual VEI002_MODELO VEI002_MODELO { get; set; }
        public virtual VEI003_COMBUSTIVEL VEI003_COMBUSTIVEL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VND002_VENDA> VND002_VENDA { get; set; }
    }
}
