//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEI002_MODELO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VEI002_MODELO()
        {
            this.VEI004_MODELO_VERSAO = new HashSet<VEI004_MODELO_VERSAO>();
        }
    
        public int IdeModelo { get; set; }
        public int IdeMarca { get; set; }
        public string CodModelo { get; set; }
        public string NmeModelo { get; set; }
    
        public virtual VEI001_MARCA VEI001_MARCA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VEI004_MODELO_VERSAO> VEI004_MODELO_VERSAO { get; set; }
    }
}
